apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p01-streaming

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - kafka.yaml
  - topics.yaml
  - bridge.yaml

labels:
  - includeSelectors: false
    pairs:
      project_ref: p01-streaming
